### ISSUE TITLE
Organize functions

### ISSUE THREAD

**Issue by mridlen** [mridlen/encoderlogic#17]
The code is all in one big block and needs to be broken down into smaller bite sized pieces

**Comment by mridlen** [comment]
Probably need to use RequireJS for this

**Comment by mridlen** [comment]
Did some quick poking and this is going to be much harder than I previously thought.

All my functions are loaded under

$(function() {
    $('#term').terminal(function(cmd, term) {

So I'm not sure how to modularize that.

I can call "alert("hello world");" from modules/test.js, but I can't call "term.echo("hello world");"

I'll have to do some more research to get this working.

**Comment by mridlen** [comment]
I've optimized all the commands and placed them into functions. I'll get with some experts on how to modularize this further. And I have RequireJS working as desired.

**Comment by mridlen** [comment]
I've removed the functions.js and made it dynamic, so that it automatically loads all js files in the commands directory (this will help future proof it)

**Comment by mridlen** [comment]
I've completely restructured terminal.js. I've moved some stuff around so that it doesn't load the directory_listing.php every time you run a command, and I think it's more efficient now.

I would still like to figure out a way to make the command interpreter more modular (ideally so that the commands can be bundled with the functions)

**Comment by mridlen** [comment]
I've switched from RequireJS to $script.js because all I'm using it for is a dependency loader. It loads much faster and it's easier to work with.

**Comment by mridlen** [comment]
interpreter.php is now dynamically generated in to a single file from cmd files

I need to do something similar with the help menu

**Comment by mridlen** [comment]
So I have an idea of how I want to proceed.

I want to have a file format that looks something like this:

---

+++FUNCTION+++
function blah () {
    //code
}
+++COMMAND+++
if (cmd.split(" ")[0] == 'blah') {
        //code
    }
+++HELP+++
term.echo("blah");

---

Then it would be parsed via php into one large file with all the code. The modules would stay separate so they could be dropped in and pulled out at will. There may be some core components that share other plugins, but hopefully this will at least allow users to create a single module that can be simply dropped in the directory.

**Comment by philtr** [comment]
``` javascript
// somewhere
var commands = [];

// modules/blah.js
commands << {
  help: "blah",
  triggers: [ "blah" ],
  fn: function(term, cmd) { this.another_thing(cmd); },
  anotherThing: function(params) { doOtherStuff(); }
}

// your command parser
for(command in commands) {
  if (command.triggers.contains(cmd.split(" ")[0])) {
    command.fn(term, cmd);
  }
}
```

---

``` javascript
// somewhere
var commands = [];

// modules/blah.js
commands << {
  triggers: [
    {
      trigger: "blah",
      help: "blah does cool stuff"
    },
    {
      trigger: "halb",
      help: "blah, but backwards"
    }
  ]

  fn: function(trigger, term, cmd) { this.another_thing(cmd); },
  anotherThing: function(params) { doOtherStuff(); }
}

// command parser
for(i = 0; i < commands.length; i++) {
  command = commands[i];

  for(j = 0; j < command.triggers.length; j++) {
    trigger = command.triggers[j];

    if(cmd.split(" ")[0] == trigger.trigger) {
      command.fn(trigger, term, cmd);
    }
  }
}
```

**Comment by mridlen** [comment]
In javascript I think it would look like:

``` javascript
commands.push ({
  triggers: [
    {
      trigger: "blah",
      help: "blah does cool stuff",
      requireLoggedIn: false
    },
    {
      trigger: "halb",
      help: "blah, but backwards",
      requireLoggedIn: true
    }
  ]

  fn: function(trigger, term, cmd) { this.another_thing(cmd); },
  anotherThing: function(params) { doOtherStuff(); }
});
```

(also I added the requireLoggedIn property so I can display the help menu accordingly)

**Comment by mridlen** [comment]
help.js is going to look like this

``` javascript
function help(term) {
    term.echo("\n=== Available commands ===\n");

    for(i = 0; i < commands.length; i++) {
        command = commands[i];
        for(j = 0; j < command.triggers.length; j++) {
            trigger = command.triggers[j];
            if ((loggedIn == false && command.trigger.requireLoggedIn == false) || loggedIn == true) {
                term.echo(command.trigger.help);
            }
        }
    }
}
```

**Comment by mridlen** [comment]
I'm going to go ahead and close this issue since the new command interpreter is in place and everything is much more organized.
